version: '2'
services:
  db:
    container_name: pg-docker
    image: postgres
    volumes:
      - /Users/nguyen_h/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    container_name: nifty-hodgkin
    image: graphqlperson
    depends_on:
      - db
    environment:
      POSTGRES_DB_HOST: db
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_USERNAME: postgres
      POSTGRES_DB_PASSWORD: docker
    ports:
      - 8080:8080